{
 "title": "tinkoff-candle-streamer-dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Доступен ли PostgreSQL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Общее количество обработанных свечей",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(processed_candles_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество вставленных строк в базу данных",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{datname=\"postgres\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Размер базы данных (Мегабайты)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"postgres\"} / 1024 / 1024",
     "legendFormat": "postgres"
    }
   ]
  },
  {
   "title": "Общее количество полученных свечей",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(get_candles_total)", "legendFormat": "__auto" }
   ]
  }
 ]
}